web:
  name: sven-demo
  port: :8888
  mode: debug

mysql:
  host: 127.0.0.1
  port: 3306
  username: admin
  password: password
  database: datename
  parameter: charset=utf8mb4&parseTime=true&loc=Local
  maxIdle: 50
  maxOpen: 100




redis:
  urls:
    - 127.0.0.1:6379
    - 127.0.0.1:6380
    - 127.0.0.1:6381
  host: 127.0.0.1
  port: 6379
  password: password
  db: 1

logger:
  filename: E:\goproject\src\logs\sven.log     #日志文件目录 绝对路径
  maxsize: 20                 #单个日志文件大小
  maxbackups: 5               #保留旧文件最大个数
  maxage: 30                  #保留旧文件最大天数

